baseURL = "https://tomsmith.design/"
languageCode = "en-us"
title = "Tom Smith Design"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    identifier = "Portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 1

  [[menu.main]]
    identifier = "Quick-View Portfolio"
    name = "Quick-View Portfolio"
    url = "/quick-view-portfolio/"
    weight = 2

  [[menu.main]]
    identifier = "list"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

   [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/media/thomas%20smith%20resum%C3%A9%202025.pdf"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6
