[build]
  command = "npm run build:css && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.143.1"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  NODE_VERSION = "20"
